language: go

go:
  - 1.2
  - 1.2.1
  - tip

install:
  - go get -v github.com/mattn/go-sqlite3
  - go get -v github.com/naoina/kocha
  - go get -v github.com/naoina/kocha/kocha

script:
  - go test ./...
